import assets from '../assets';
const Data = {
  productItems : [
    {
      id : 1,
      discount : 0,
      cover : assets.images.flash.flash1,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
    {
      id : 2,
      discount : 50,
      cover : assets.images.flash.flash2,
      name : 'Watch',
      price : 20,
      rating : 5,
    },
    {
      id : 3,
      discount : 0,
      cover : assets.images.flash.flash3,
      name : 'Smart Mobile Black',
      price : 200,
      rating : 3.5,
    },
    {
      id : 4,
      discount : 0,
      cover : assets.images.flash.flash4,
      name : 'Smart Watch Black',
      price : 25,
      rating : 4.5,
    },
    {
      id : 5,
      discount : 13,
      cover : assets.images.flash.flash5,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
    {
      id : 6,
      discount : 0,
      cover : assets.images.flash.flash1,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
  ],
  allProducts : [
    {
      id : 1,
      discount : 0,
      cover : assets.images.flash.flash1,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
    {
      id : 2,
      discount : 50,
      cover : assets.images.flash.flash2,
      name : 'Watch',
      price : 20,
      rating : 5,
    },
    {
      id : 3,
      discount : 0,
      cover : assets.images.flash.flash3,
      name : 'Smart Mobile Black',
      price : 200,
      rating : 3.5,
    },
    {
      id : 4,
      discount : 0,
      cover : assets.images.flash.flash4,
      name : 'Smart Watch Black',
      price : 25,
      rating : 4.5,
    },
    {
      id : 5,
      discount : 13,
      cover : assets.images.flash.flash5,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
    {
      id : 6,
      discount : 0,
      cover : assets.images.flash.flash1,
      name : 'Shoes',
      price : 100,
      rating : 4,
    },
    {
      id : 7,
      discount : 0,
      cover : assets.images.shops.shop1,
      name : 'Headphone',
      price : 100,
      rating : 4,
    },
  ],
};
export default Data;
